[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$W8t5j/F.7x1DSMn5H6MUQg$fPiB9bHfdl1UAOgWKLfggv1cpVkAulkxW/E.8Ye1/Ehos2U4r6VR5VCQzDWlcmVOsFh5iisQ1uiV26Uqz1HQ5w

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
